### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-bower-registry#257]
In the future Origami will only support NPM. 
https://github.com/Financial-Times/origami/pull/86/

Early 2021, after other communications have gone out, our Bower registry can be marked as deprecated in [bizops](https://biz-ops.in.ft.com/System/origami-bower-registry).

**Comment by JakeChampion** [comment]
I've done the work for this -- https://github.com/Financial-Times/origami-bower-registry/pull/289
